#pragma once

#include <MUI.h>

// This file was generated by MUI Visual Designer 0.0.1
// WARNING: Changes to this file may cause incorrect behavior and will be lost if
//          the code is regenerated.

class MainWindowBase : public mui::Window
{
protected:
	void InitializeComponent()
	{
		SetTitle(L"MUI Visual Designer");
		SetHeight(600);
		SetWidth(800);
		SetCaptionColor(RGB(24, 24, 24));
		std::shared_ptr<mui::Grid> Grid1 = std::make_shared<mui::Grid>();
		Grid1->SetBackgroundColor(RGB(24, 24, 24));
		Grid1->AddRow(mui::RowDefinition(mui::GridLength::Auto()));
		Grid1->AddRow(mui::RowDefinition(mui::GridLength(2, mui::GridUnitType::Star)));
		Grid1->AddRow(mui::RowDefinition(mui::GridLength::Star()));
		Grid1->AddColumn(mui::ColumnDefinition(mui::GridLength::Star()));
		Grid1->AddColumn(mui::ColumnDefinition(mui::GridLength(4, mui::GridUnitType::Star)));
		Grid1->AddColumn(mui::ColumnDefinition(mui::GridLength::Star()));
		std::shared_ptr<mui::Label> Label10 = std::make_shared<mui::Label>(L"Project Explorer");
		Label10->SetHorizontalAlignment(mui::LayoutAlignment::Center);
		Label10->SetTextColor(RGB(255, 255, 255));
		std::shared_ptr<mui::Label> Label11 = std::make_shared<mui::Label>(L"Window Preview");
		Label11->SetHorizontalAlignment(mui::LayoutAlignment::Center);
		Label11->SetTextColor(RGB(255, 255, 255));
		std::shared_ptr<mui::Label> Label12 = std::make_shared<mui::Label>(L"Properties");
		Label12->SetHorizontalAlignment(mui::LayoutAlignment::Center);
		Label12->SetTextColor(RGB(255, 255, 255));
		std::shared_ptr<mui::TreeView> TreeView13 = std::make_shared<mui::TreeView>();
		TreeView13->SetBackgroundColor(RGB(24, 24, 24));
		windowHost = std::make_shared<mui::NativeWindowHost>();
		windowHost->SetBorder(TRUE);
		windowHost->SetBackgroundColor(RGB(24, 24, 24));
		windowHost->OnResize = std::bind(&MainWindowBase::WindowHost_OnResize, this, std::placeholders::_1, std::placeholders::_2);
		designerEntry = std::make_shared<mui::Entry>(L"");
		designerEntry->SetBackgroundColor(RGB(24, 24, 24));
		designerEntry->SetMultiline(TRUE);
		designerEntry->SetTextColor(RGB(255, 255, 255));
		designerEntry->NewLine = std::bind(&MainWindowBase::Entry_NewLine, this, std::placeholders::_1, std::placeholders::_2);
		designerEntry->CharPressed = std::bind(&MainWindowBase::Entry_CharPressed, this, std::placeholders::_1, std::placeholders::_2);
		designerEntry->Save = std::bind(&MainWindowBase::Entry_Save, this, std::placeholders::_1, std::placeholders::_2);
		debugEntry = std::make_shared<mui::Entry>(L"");
		debugEntry->SetBackgroundColor(RGB(24, 24, 24));
		debugEntry->SetMultiline(TRUE);
		debugEntry->SetTextColor(RGB(255, 255, 255));
		Grid1->AddChild(Label10);
		Grid1->SetRow(Label10, 0);
		Grid1->SetColumn(Label10, 0);
		Grid1->AddChild(Label11);
		Grid1->SetRow(Label11, 0);
		Grid1->SetColumn(Label11, 1);
		Grid1->AddChild(Label12);
		Grid1->SetRow(Label12, 0);
		Grid1->SetColumn(Label12, 2);
		Grid1->AddChild(TreeView13);
		Grid1->SetRow(TreeView13, 1);
		Grid1->SetColumn(TreeView13, 0);
		Grid1->SetRowSpan(TreeView13, 2);
		Grid1->AddChild(windowHost);
		Grid1->SetRow(windowHost, 1);
		Grid1->SetColumn(windowHost, 1);
		Grid1->AddChild(designerEntry);
		Grid1->SetRow(designerEntry, 2);
		Grid1->SetColumn(designerEntry, 1);
		Grid1->AddChild(debugEntry);
		Grid1->SetRow(debugEntry, 1);
		Grid1->SetColumn(debugEntry, 2);
		Grid1->SetRowSpan(debugEntry, 2);
		SetContent(Grid1);
		OnClose = std::bind(&MainWindowBase::MainWindow_OnClose, this, std::placeholders::_1, std::placeholders::_2);
		KeyDown = std::bind(&MainWindowBase::MainWindow_KeyDown, this, std::placeholders::_1, std::placeholders::_2);
	}

	virtual void Entry_CharPressed(const void* sender, mui::EventArgs_t* e) = 0;
	virtual void Entry_NewLine(const void* sender, mui::EventArgs_t* e) = 0;
	virtual void Entry_Save(const void* sender, mui::EventArgs_t* e) = 0;
	virtual void MainWindow_KeyDown(const void* sender, mui::EventArgs_t* e) = 0;
	virtual void WindowHost_OnResize(const void* sender, mui::EventArgs_t* e) = 0;
	std::shared_ptr<mui::NativeWindowHost> windowHost;
	std::shared_ptr<mui::Entry> designerEntry;
	std::shared_ptr<mui::Entry> debugEntry;
	virtual void MainWindow_OnClose(const void* sender, mui::EventArgs_t* e) = 0;
};
