#pragma once

#include <MUI.h>

// This file was generated by MUI Visual Designer 0.0.1
// WARNING: Changes to this file may cause incorrect behavior and will be lost if
//          the code is regenerated.

class MainWindowBase : public mui::Window
{
protected:
	void InitializeComponent()
	{
		SetTitle(L"MUI Visual Designer");
		SetHeight(600);
		SetWidth(800);
		std::shared_ptr<mui::Menu> Menu1 = std::make_shared<mui::Menu>();
		Menu1->SetBackgroundColor(RGB(24, 24, 24));
		Menu1->SetTextColor(RGB(255, 255, 255));
		Menu1->SetBottomBarColor(RGB(48, 48, 48));
		Menu1->SetItemBackgroundColor(RGB(24, 24, 24));
		Menu1->SetItemBackgroundHotColor(RGB(36, 36, 36));
		Menu1->SetItemBackgroundSelectedColor(RGB(32, 32, 32));
		std::shared_ptr<mui::MenuItem> MenuItem2 = std::make_shared<mui::MenuItem>(L"File");
		std::shared_ptr<mui::MenuItem> MenuItem3 = std::make_shared<mui::MenuItem>(L"Open");
		MenuItem3->OnClick = std::bind(&MainWindowBase::File_Open, this, std::placeholders::_1, std::placeholders::_2);
		MenuItem2->AddMenuItem(MenuItem3);
		std::shared_ptr<mui::MenuItem> MenuItem4 = std::make_shared<mui::MenuItem>(L"Close");
		MenuItem4->OnClick = std::bind(&MainWindowBase::File_Close, this, std::placeholders::_1, std::placeholders::_2);
		MenuItem2->AddMenuItem(MenuItem4);
		MenuItem2->AddSeparator();
		std::shared_ptr<mui::MenuItem> MenuItem6 = std::make_shared<mui::MenuItem>(L"Exit");
		MenuItem6->OnClick = std::bind(&MainWindowBase::File_Exit, this, std::placeholders::_1, std::placeholders::_2);
		MenuItem2->AddMenuItem(MenuItem6);
		Menu1->AddMenuItem(MenuItem2);
		std::shared_ptr<mui::MenuItem> MenuItem7 = std::make_shared<mui::MenuItem>(L"Help");
		std::shared_ptr<mui::MenuItem> MenuItem8 = std::make_shared<mui::MenuItem>(L"About");
		MenuItem8->OnClick = std::bind(&MainWindowBase::Help_About, this, std::placeholders::_1, std::placeholders::_2);
		MenuItem7->AddMenuItem(MenuItem8);
		Menu1->AddMenuItem(MenuItem7);
		SetMenu(Menu1); 
		std::shared_ptr<mui::Grid> Grid9 = std::make_shared<mui::Grid>();
		Grid9->SetBackgroundColor(RGB(24, 24, 24));
		Grid9->AddRow(mui::RowDefinition(mui::GridLength::Auto()));
		Grid9->AddRow(mui::RowDefinition(mui::GridLength(2, mui::GridUnitType::Star)));
		Grid9->AddRow(mui::RowDefinition(mui::GridLength::Star()));
		Grid9->AddColumn(mui::ColumnDefinition(mui::GridLength(6, mui::GridUnitType::Star)));
		std::shared_ptr<mui::Label> Label16 = std::make_shared<mui::Label>(L"Window Preview");
		Label16->SetHorizontalAlignment(mui::LayoutAlignment::Center);
		Label16->SetTextColor(RGB(255, 255, 255));
		std::shared_ptr<mui::Grid> Grid17 = std::make_shared<mui::Grid>();
		Grid17->SetBorder(TRUE);
		Grid17->SetBackgroundColor(RGB(26, 26, 26));
		fakeWindowGrid = std::make_shared<mui::Grid>();
		fakeWindowGrid->SetVerticalAlignment(mui::LayoutAlignment::Center);
		fakeWindowGrid->SetHorizontalAlignment(mui::LayoutAlignment::Center);
		fakeWindowGrid->SetVisible(FALSE);
		fakeWindowGrid->AddRow(mui::RowDefinition(mui::GridLength::Auto()));
		fakeWindowGrid->AddRow(mui::RowDefinition(mui::GridLength::Auto()));
		fakeWindowGrid->AddColumn(mui::ColumnDefinition(mui::GridLength::Auto()));
		windowCaption = std::make_shared<mui::StackLayout>(mui::StackLayoutOrientation::Horizontal);
		windowCaption->SetBorder(TRUE);
		windowCaption->SetBackgroundColor(RGB(255, 255, 255));
		windowTitleLabel = std::make_shared<mui::Label>(L"");
		windowCaption->Children().Add(windowTitleLabel);
		windowHost = std::make_shared<mui::NativeWindowHost>();
		windowHost->SetBorder(TRUE);
		windowHost->OnResize = std::bind(&MainWindowBase::WindowHost_OnResize, this, std::placeholders::_1, std::placeholders::_2);
		fakeWindowGrid->AddChild(windowCaption);
		fakeWindowGrid->SetRow(windowCaption, 0);
		fakeWindowGrid->AddChild(windowHost);
		fakeWindowGrid->SetRow(windowHost, 1);
		Grid17->AddChild(fakeWindowGrid);
		designerEntry = std::make_shared<mui::Entry>(L"");
		designerEntry->SetBackgroundColor(RGB(24, 24, 24));
		designerEntry->KeyDown = std::bind(&MainWindowBase::Entry_KeyDown, this, std::placeholders::_1, std::placeholders::_2);
		designerEntry->SetMultiline(TRUE);
		designerEntry->SetTextColor(RGB(255, 255, 255));
		designerEntry->NewLine = std::bind(&MainWindowBase::Entry_NewLine, this, std::placeholders::_1, std::placeholders::_2);
		designerEntry->CharPressed = std::bind(&MainWindowBase::Entry_CharPressed, this, std::placeholders::_1, std::placeholders::_2);
		designerEntry->Save = std::bind(&MainWindowBase::Entry_Save, this, std::placeholders::_1, std::placeholders::_2);
		Grid9->AddChild(Label16);
		Grid9->SetRow(Label16, 0);
		Grid9->SetColumn(Label16, 0);
		Grid9->AddChild(Grid17);
		Grid9->SetRow(Grid17, 1);
		Grid9->SetColumn(Grid17, 0);
		Grid9->AddChild(designerEntry);
		Grid9->SetRow(designerEntry, 2);
		Grid9->SetColumn(designerEntry, 0);
		SetContent(Grid9);
		OnClose = std::bind(&MainWindowBase::MainWindow_OnClose, this, std::placeholders::_1, std::placeholders::_2);
		KeyDown = std::bind(&MainWindowBase::MainWindow_KeyDown, this, std::placeholders::_1, std::placeholders::_2);
		DragAndDrop = std::bind(&MainWindowBase::MainWindow_DragAndDrop, this, std::placeholders::_1, std::placeholders::_2);
	}

	virtual void Entry_CharPressed(const void* sender, mui::EventArgs_t* e) = 0;
	virtual void Entry_KeyDown(const void* sender, mui::EventArgs_t* e) = 0;
	virtual void Entry_NewLine(const void* sender, mui::EventArgs_t* e) = 0;
	virtual void Entry_Save(const void* sender, mui::EventArgs_t* e) = 0;
	virtual void File_Close(const void* sender, mui::EventArgs_t* e) = 0;
	virtual void File_Exit(const void* sender, mui::EventArgs_t* e) = 0;
	virtual void File_Open(const void* sender, mui::EventArgs_t* e) = 0;
	virtual void Help_About(const void* sender, mui::EventArgs_t* e) = 0;
	virtual void MainWindow_KeyDown(const void* sender, mui::EventArgs_t* e) = 0;
	virtual void WindowHost_OnResize(const void* sender, mui::EventArgs_t* e) = 0;
	std::shared_ptr<mui::Grid> fakeWindowGrid;
	std::shared_ptr<mui::StackLayout> windowCaption;
	std::shared_ptr<mui::Label> windowTitleLabel;
	std::shared_ptr<mui::NativeWindowHost> windowHost;
	std::shared_ptr<mui::Entry> designerEntry;
	virtual void MainWindow_OnClose(const void* sender, mui::EventArgs_t* e) = 0;
	virtual void MainWindow_DragAndDrop(const void* sender, mui::EventArgs_t* e) = 0;
};
