#pragma once
#include "IGenerator.h"
#include "MenuGenerator.h"
#include "resource.h"

class WindowGenerator : public GeneratorBase {
public:
    std::shared_ptr<mui::Window> CreateWindowPreview() override
    {
        std::wstring title = GetProperty(L"Title");
        std::wstring heightStr = GetProperty(L"Height");
        std::wstring widthStr = GetProperty(L"Width");
        size_t height = 500;
        size_t width = 500;
        if (!heightStr.empty())
            height = std::stoi(heightStr.c_str());
        if (!widthStr.empty())
            width = std::stoi(widthStr.c_str());

        std::shared_ptr<mui::Window> wind = std::make_shared<mui::Window>(title, height, width);

        std::wstring maxWidth = GetProperty(L"MaxWidth");
        if (!maxWidth.empty())
            wind->SetMaxWidth(std::stoi(maxWidth.c_str()));

        std::wstring minWidth = GetProperty(L"MinWidth");
        if (!minWidth.empty())
            wind->SetMinWidth(std::stoi(minWidth.c_str()));

        std::wstring maxHeight = GetProperty(L"MaxHeight");
        if (!maxHeight.empty())
            wind->SetMaxHeight(std::stoi(maxHeight.c_str()));

        std::wstring minHeight = GetProperty(L"MinHeight");
        if (!minHeight.empty())
            wind->SetMinHeight(std::stoi(minHeight.c_str()));

        std::wstring captionColor = GetProperty(L"CaptionColor");
        if (!captionColor.empty()) {
            COLORREF color = ParseColor(captionColor);
            if (color != CLR_INVALID) {
                wind->SetCaptionColor(color);
            }
        }

        std::wstring backgroundColor = GetProperty(L"BackgroundColor");
        if (!backgroundColor.empty()) {
            COLORREF color = ParseColor(backgroundColor);
            if (color != CLR_INVALID) {
                wind->SetBackgroundColor(color);
            }
        }

        std::shared_ptr<MenuGenerator> menuGen = NULL;
        std::shared_ptr<GeneratorBase> contentGen = NULL;

        for (const auto& child : children) {
            if (child->GetElementName() == L"Menu") {
                menuGen = std::dynamic_pointer_cast<MenuGenerator>(child);
            }
            else {
                contentGen = child;
            }
        }

        if (menuGen) {
            auto menu = menuGen->CreateMenuPreview();
            if (menu) {
                wind->SetMenu(menu);
            }
        }

        return wind;
    }

    std::wstring Generate() override
    {
        std::wstring output;
        std::wstring className = GetProperty(L"Class");
        output += L"#pragma once\r\n\r\n#include <MUI.h>\r\n\r\n";
        output += L"// This file was generated by MUI Visual Designer " MVD_WVERSION L"\r\n// WARNING: Changes to this file may cause incorrect behavior and will be lost if\r\n//          the code is regenerated.\r\n\r\n";
        output += L"class " + className + L"Base : public mui::Window\r\n{\r\nprotected:\r\n\tvoid InitializeComponent()\r\n\t{\r\n";

        std::wstring title = GetProperty(L"Title");
        if (!title.empty())
            output += L"\t\tSetTitle(L\"" + EscapeString(title) + L"\");\r\n";
        std::wstring height = GetProperty(L"Height");
        if (!height.empty())
            output += L"\t\tSetHeight(" + height + L");\r\n";
        std::wstring width = GetProperty(L"Width");
        if (!width.empty())
            output += L"\t\tSetWidth(" + width + L");\r\n";

        std::wstring maxWidth = GetProperty(L"MaxWidth");
        if (!maxWidth.empty())
            output += L"\t\tSetMaxWidth(" + maxWidth + L");\r\n";
        std::wstring minWidth = GetProperty(L"MinWidth");
        if (!minWidth.empty())
            output += L"\t\tSetMinWidth(" + minWidth + L");\r\n";
        std::wstring maxHeight = GetProperty(L"MaxHeight");
        if (!maxHeight.empty())
            output += L"\t\tSetMaxHeight(" + maxHeight + L");\r\n";
        std::wstring minHeight = GetProperty(L"MinHeight");
        if (!minHeight.empty())
            output += L"\t\tSetMinHeight(" + minHeight + L");\r\n";

        std::wstring captionColor = GetProperty(L"CaptionColor");
        if (!captionColor.empty()) {
            COLORREF color = ParseColor(captionColor);
            if (color != CLR_INVALID) {
                int r = GetRValue(color);
                int g = GetGValue(color);
                int b = GetBValue(color);
                output += L"\t\tSetCaptionColor(RGB(" +
                    std::to_wstring(r) + L", " + std::to_wstring(g) + L", " + std::to_wstring(b) + L"));\r\n";
            }
        }

        std::wstring backgroundColor = GetProperty(L"BackgroundColor");
        if (!backgroundColor.empty()) {
            COLORREF color = ParseColor(backgroundColor);
            if (color != CLR_INVALID) {
                int r = GetRValue(color);
                int g = GetGValue(color);
                int b = GetBValue(color);
                output += L"\t\tSetBackgroundColor(RGB(" +
                    std::to_wstring(r) + L", " + std::to_wstring(g) + L", " + std::to_wstring(b) + L"));\r\n";
            }
        }

        std::shared_ptr<GeneratorBase> menuChild = NULL;
        std::shared_ptr<GeneratorBase> contentChild = NULL;

        for (const auto& child : children) {
            if (child->GetElementName() == L"Menu") {
                menuChild = child;
            }
            else {
                contentChild = child;
            }
        }

        if (menuChild) {
            output += menuChild->Generate();
            std::wstring menuVarName = menuChild->GetVariableName();
            output += L"\t\tSetMenu(" + menuVarName + L"); \r\n";
        }

        if (contentChild) {
            output += contentChild->Generate();
            std::wstring contentVarName = contentChild->GetVariableName();
            output += L"\t\tSetContent(" + contentVarName + L");\r\n";
        }
        else if (children.size() == 1 && !menuChild) {
            output += children[0]->Generate();
            std::wstring childVarName = children[0]->GetVariableName();
            output += L"\t\tSetContent(" + childVarName + L");\r\n";
        }

        output += GenerateWindowEventHandlers();
        output += L"\t}\r\n\r\n";
        output += UIElementGeneratorBase::CollectAllEventHandlerFunctions(UIElementGeneratorBase::s_rootGenerator);
        output += UIElementGeneratorBase::CollectAllMemberVariables(UIElementGeneratorBase::s_rootGenerator);

        const std::vector<std::wstring> events = { L"OnClose", L"DragAndDrop", L"WndProc" };

        for (const auto& eventName : events) {
            std::wstring handlerName = GetProperty(eventName);
            if (!handlerName.empty()) {
                output += L"\tvirtual void " + handlerName + L"(const void* sender, mui::EventArgs_t* e) = 0;\r\n";
            }
        }

        output += L"};\r\n";
        return output;
    }

private:
    COLORREF ParseColor(const std::wstring& colorStr) const {
        if (colorStr.empty()) return CLR_INVALID;

        if (colorStr.find(L',') != std::wstring::npos || colorStr.find(L"rgb") != std::wstring::npos) {
            std::wstring cleaned = colorStr;
            size_t start = cleaned.find(L"rgb(");
            if (start != std::wstring::npos) {
                cleaned = cleaned.substr(start + 4);
                size_t end = cleaned.find(L')');
                if (end != std::wstring::npos) {
                    cleaned = cleaned.substr(0, end);
                }
            }

            std::vector<int> values;
            std::wstring current;
            for (wchar_t c : cleaned) {
                if (c == L',' || c == L' ') {
                    if (!current.empty()) {
                        values.push_back(_wtoi(current.c_str()));
                        current.clear();
                    }
                }
                else if (c >= L'0' && c <= L'9') {
                    current += c;
                }
            }
            if (!current.empty()) {
                values.push_back(_wtoi(current.c_str()));
            }

            if (values.size() == 3) {
                return RGB(values[0], values[1], values[2]);
            }
        }

        if (colorStr[0] == L'#' || colorStr.substr(0, 2) == L"0x") {
            std::wstring hexStr = colorStr;
            if (hexStr[0] == L'#') hexStr = hexStr.substr(1);
            if (hexStr.substr(0, 2) == L"0x") hexStr = hexStr.substr(2);

            if (hexStr.length() == 6) {
                unsigned long value = wcstoul(hexStr.c_str(), nullptr, 16);
                return RGB((value >> 16) & 0xFF, (value >> 8) & 0xFF, value & 0xFF);
            }
        }

        if (colorStr == L"Red" || colorStr == L"red") return RGB(255, 0, 0);
        if (colorStr == L"Green" || colorStr == L"green") return RGB(0, 255, 0);
        if (colorStr == L"Blue" || colorStr == L"blue") return RGB(0, 0, 255);
        if (colorStr == L"White" || colorStr == L"white") return RGB(255, 255, 255);
        if (colorStr == L"Black" || colorStr == L"black") return RGB(0, 0, 0);
        if (colorStr == L"Yellow" || colorStr == L"yellow") return RGB(255, 255, 0);
        if (colorStr == L"Gray" || colorStr == L"gray") return RGB(128, 128, 128);

        return CLR_INVALID;
    }

    std::wstring GenerateWindowEventHandlers() const {
        std::wstring output;
        std::wstring className = GetProperty(L"Class") + L"Base";

        const std::vector<std::wstring> events = { L"OnClose", L"KeyDown", L"KeyUp", L"DragAndDrop", L"WndProc" };

        for (const auto& eventName : events) {
            std::wstring handlerName = GetProperty(eventName);
            if (!handlerName.empty()) {
                output += L"\t\t" + eventName + L" = std::bind(&" + className + L"::" + handlerName +
                    L", this, std::placeholders::_1, std::placeholders::_2);\r\n";
            }
        }

        return output;
    }
};